AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java25
      Handler: com.chngy.jobscraper.App::handleRequest
      Timeout: 600
      MemorySize: 512
      CodeUri: .
      Environment:
        Variables:
          CAREER_GOV_URL: https://jobs.careers.gov.sg/
          MY_CAREER_FUTURES_URL: https://www.mycareersfuture.gov.sg/
          SNS_TOPIC_NAME: arn:aws:sns:ap-southeast-1:366667683184:job-scraper-lambda-results
          S3_BUCKET_NAME: jobscraper-366667683184-ap-southeast-1-an
          S3_KEY_NAME: data/seen
          SEARCH_TERM: software+engineer
          YEARS_OF_EXPERIENCE: 4
          YEARS_OF_EXPERIENCE_BUFFER: 1
          EMPLOYMENT_TERM: perm
          SALARY: 6000
          SALARY_BUFFER: 1000
          PROFILE: prod
          JOBS: gov
          NUMBER_OF_RESULTS: 5
          FILTER_OUT_RESULTS_DAYS_AGO: 14
          LOG4J_CONFIGURATION_FILE: log4j2-prod.xml
      Tags:
        project: jobscraper
      Policies:
        - S3CrudPolicy:
            BucketName: jobscraper-366667683184-ap-southeast-1-an
        - SNSPublishMessagePolicy:
            TopicName: job-scraper-lambda-results
      Events:
        WeeklyTrigger:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
  AppFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AppFunction}
      RetentionInDays: 14
      Tags:
        - Key: project
          Value: jobscraper